[package]
name = "dijkstra"
version = "0.1.0"
edition = "2021"

[dependencies]
genawaiter = "0.99.1"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "test"
harness = false
